services:
  app:
    image: ${APP_IMAGE}
    env_file:
      - ./.env/dev_env
    container_name: bootcamp_app
    ports:
      - "80:8000"
    restart: always
    depends_on:
      - db

  db:
    image: ${DATABASE_IMAGE}
    env_file:
      - ./.env/dev_env
    container_name: bootcamp_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
