name: "Build and run docker container in EC2"

on:
  push:
    branches:
      - main
      

jobs:
  deploy-my-code:
    name: "Deploy my code in Docker container on EC2"
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ vars.SERVER_IP }}
      SERVER_USER: ${{ vars.SERVER_USER }}
      DOCKER_HUB_USER: ${{ vars.DOCKER_USER }}
      DOCKER_HUB_REPO: ${{ vars.DOCKER_REPO }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up TAG
        run: |
          echo "TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      # - name: Set up Docker Buildx 
      #   uses: docker/setup-buildx-action@v3

      # - name: Login to Dockerhub
      #   run: |
      #     echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u $DOCKER_HUB_USER --password-stdin

      # - name: Build Docker image
      #   run: |
      #     docker build -t "$DOCKER_HUB_USER/$DOCKER_HUB_REPO:$TAG" .

      # - name: Push Docker image
      #   run: | 
      #     docker push "$DOCKER_HUB_USER/$DOCKER_HUB_REPO:$TAG"

      - name: Set up for SSH connection
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
          chmod 600 ~/.ssh/config 

      - name: Add private key for ssh 
        run: |
          echo $SSH_KEY64 | base64 -d >> mykey.pem
          chmod 400 mykey.pem 
          ssh-keygen -R $SERVER_IP
        env: 
          SSH_KEY64: ${{ secrets.SSH_KEY64 }}
      
      - name: Make ssh connection, pull and run docker image
        run: |
          ssh -i mykey.pem $SERVER_USER@$SERVER_IP "
          docker pull $DOCKER_HUB_USER/$DOCKER_HUB_REPO:1.0.0
          docker pull postgres:15

          # run postgres
          docker run -d \
            --name db \
            -e POSTGRES_USER=$POSTGRES_USER
            -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            -e POSTGRES_DB=$POSTGRES_DB
            -p 5432:5432 \
            postgres:15
          
          # run app
          docker run -d \
            --name app \
            -e POSTGRES_USER=$POSTGRES_USER
            -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            -e POSTGRES_DB=$POSTGRES_DB
            -p 80:8080 \
            -v postgres_data:/var/lib/postgresql/data \
            --link db:db \
            $DOCKER_HUB_USER/$DOCKER_HUB_REPO:1.0.0
          "
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          DOCKER_HUB_USER: $DOCKER_HUB_USER
          DOCKER_HUB_REPO: $DOCKER_HUB_REPO
          TAG: $TAG
              


           



