name: "Build and run docker container in EC2"

on:
  push:
    branches:
      - main
      

jobs:
  deploy-my-code:
    name: "Deploy my code in Docker container on EC2"
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ vars.SERVER_IP }}
      SERVER_USER: ${{ vars.SERVER_USER }}
      DOCKER_HUB_USER: ${{ vars.DOCKER_USER }}
      DOCKER_HUB_REPO: ${{ vars.DOCKER_REPO }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up TAG
        run: |
          echo "TAG=latest" >> $GITHUB_ENV

      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u $DOCKER_HUB_USER --password-stdin

      - name: Build Docker image
        run: |
          docker build -t "$DOCKER_HUB_USER/$DOCKER_HUB_REPO:$TAG" .

      - name: Push Docker image
        run: | 
          docker push "$DOCKER_HUB_USER/$DOCKER_HUB_REPO:$TAG"

      - name: Set up for SSH connection
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
          chmod 600 ~/.ssh/config 

      - name: Add private key for ssh 
        run: |
          echo "$SSH_KEY64" | base64 -d >> mykey.pem
          chmod 400 mykey.pem 
          touch ~/.ssh/known_hosts
          ssh-keygen -R $SERVER_IP
        env: 
          SSH_KEY64: ${{ secrets.SSH_KEY64 }}
      
      - name: Copy docker-compose file
        run: |
          scp -i mykey.pem ./docker-compose.yaml $SERVER_USER@$SERVER_IP:~/
      
      - name: Make ssh connection, pull and run docker image
        run: |
          ssh -i mykey.pem $SERVER_USER@$SERVER_IP "
          docker compose --env-file ./.env/dev_env pull
          docker compose --env-file ./.env/dev_env down -v
          docker compose --env-file ./.env/dev_env up -d
          "
              


           



